dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker

language: c

before_install:
  - git clone https://github.com/S3rg7o/sancus-main.git # Sergio Install's custom Sancus core - DMA support
  - cd sancus-main/docker && make build SANCUS_SECURITY=$SECURITY 
 
script:
  - docker run -t sancus-devel /bin/sh -c \
        "cd /sancus/sancus-examples && git checkout $TRAVIS_BRANCH &&
         make SANCUS_SECURITY=$SECURITY $TARGET.sim"
  - docker ps -a

env:
  #- TARGET=hello-world          SECURITY=64
  - TARGET=hello-DMA	         SECURITY=64
  - TARGET=attack-one-by-one     SECURITY=64
  - TARGET=attack-presaved-data  SECURITY=64
  - TARGET=MMIO_DMA_op           SECURITY=64
  #- TARGET=sensor-reader-mod     SECURITY=64
  #- TARGET=memory-access-bug    SECURITY=64	
  #- TARGET=hello-world          SECURITY=128
  #- TARGET=sensor-reader        SECURITY=64
  #- TARGET=arithmetic           SECURITY=64
  #- TARGET=fileio               SECURITY=64
  #- TARGET=timer                SECURITY=64
  
